version: '2'
services:
  dashboard_web:
    ports:
     - "80:80"
    volumes:
     - ../src:/var/www
     - ../bin:/var/www/bin
     - ./apache/sites-enabled:/etc/apache2/sites-enabled
    links:
     - dashboard_db
    container_name: dashboard_web
    build:
      context: ./apache
    environment:
        XDEBUG_CONFIG: remote_host=10.0.75.1
        PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/var/www/bin
    networks:
      - dashboard-network
  dashboard_db:
    ports:
     - "3306:3306"
    volumes:
     - storage:/data/db
    container_name: dashboard_db
    image: mariadb
    environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - dashboard-network
volumes:
  storage: {}
networks:
  dashboard-network:
